GET  http://localhost:5000/requirements/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiZW1haWwiOiJ2YWxkZW1hci5sZW9udGV2QGdtYWlsLmNvbSIsInJvbGVJZCI6IjIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBRE1JTiIsIm5iZiI6MTY2NTE1NDUyNywiZXhwIjoxNjY1MTU0NTg3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.WCFQ2Jza8qGdumyWqSBK_PTaysTG9_q7dT2-NW0gCIg

###
GET http://localhost:5000/profiles/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiZW1haWwiOiJ2YWxkZW1hci5sZW9udGV2QGdtYWlsLmNvbSIsInJvbGVJZCI6IjIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBRE1JTiIsIm5iZiI6MTY2NTE1NDUyNywiZXhwIjoxNjY1MTU0NTg3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.WCFQ2Jza8qGdumyWqSBK_PTaysTG9_q7dT2-NW0gCIg