GET http://localhost:5000/profiles/list?subdivisionId
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiZW1haWwiOiJ2YWxkZW1hci5sZW9udGV2QGdtYWlsLmNvbSIsInJvbGVJZCI6IjIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBRE1JTiIsIm5iZiI6MTY2NjAwMTYxMiwiZXhwIjoxNjY2MDAxNjcyLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.f97lg5vyMHg9HgM2RMoehrwbPRCG9bgE14Pzk_cspV8