create table business.requirement_link_file
(
    id             integer generated by default as identity
        constraint pk_requirement_link_file
            primary key,
    requirement_id integer not null
        constraint fk_requirement_link_file_requirement_requirement_id
            references business.requirement
            on delete cascade,
    file_id        integer not null
        constraint fk_requirement_link_file_file_data_model_file_id
            references business.file
            on delete cascade
);

alter table business.requirement_link_file
    owner to postgres;

create index ix_requirement_link_file_file_id
    on business.requirement_link_file (file_id);

create index ix_requirement_link_file_requirement_id
    on business.requirement_link_file (requirement_id);



alter table business.file add column hash varchar(64)