create table business.requirement_response
(
    id                integer generated by default as identity
        constraint pk_requirement_response
            primary key,
    requirement_id    integer       not null
        constraint fk_requirement_response_requirement_requirement_id
            references business.requirement
            on delete cascade,
    sender_profile_id integer       not null
        constraint fk_requirement_response_profile_profile_id
            references business.profile
            on delete cascade,
    description       varchar(1024) not null
);

alter table business.requirement_response
    owner to postgres;

create index ix_requirement_response_requirement_id
    on business.requirement_response (requirement_id);

create index ix_requirement_response_sender_profile_id
    on business.requirement_response (sender_profile_id);




alter table business.requirement_stage
    add column requirement_response_id int null;

alter table business.requirement_stage
    add constraint fk_requirement_stage_requirement_response_requirement
        foreign key (requirement_response_id) references business.requirement_response;

create index ix_requirement_stage_requirement_response_id
    on business.requirement_stage (requirement_response_id);
