create schema if not exists tests;

drop table if exists tests.test;

create table tests.test
(
    id integer not null generated by default as identity,
    name varchar(32) not null,

    constraint pk_tests_test primary key (id)
);