-- 1. Creating dictionary.requirement_category_type 

drop table if exists dictionaries.requirement_category_type;

create table dictionaries.requirement_category_type
(
    id          integer generated by default as identity
        constraint pk_requirement_category_type
            primary key,
    description text not null
);

alter table dictionaries.requirement_category_type
    owner to postgres;

create unique index if not exists ix_requirement_category_type_description
    on dictionaries.requirement_category_type (description);

-- 2. Update dictionary.requirement_category

update dictionaries.requirement_category set description = TRIM(BOTH ' ' FROM  split_part(description, ' / ', 2));

alter table dictionaries.requirement_category
    add column requirement_category_type_id int;


INSERT INTO dictionaries.requirement_category_type (id, description) VALUES (1, 'Интернет');
INSERT INTO dictionaries.requirement_category_type (id, description) VALUES (2, 'Компьютерная техника');
INSERT INTO dictionaries.requirement_category_type (id, description) VALUES (3, 'Корпоративная почта');
INSERT INTO dictionaries.requirement_category_type (id, description) VALUES (4, 'Мобильная связь');
INSERT INTO dictionaries.requirement_category_type (id, description) VALUES (5, 'Мобильные устройства');
INSERT INTO dictionaries.requirement_category_type (id, description) VALUES (6, 'Программное обеспечение');
INSERT INTO dictionaries.requirement_category_type (id, description) VALUES (7, 'Сетевое оборудование');
INSERT INTO dictionaries.requirement_category_type (id, description) VALUES (8, 'Электронная подпись');
INSERT INTO dictionaries.requirement_category_type (id, description) VALUES (9, 'IP-Телефония');

UPDATE dictionaries.requirement_category SET description = 'Отсутствие доступа к сайту', has_agreement = false, requirement_category_type_id = 1 WHERE id = 1;
UPDATE dictionaries.requirement_category SET description = 'Подключение к онлайн конференции', has_agreement = false, requirement_category_type_id = 1 WHERE id = 2;
UPDATE dictionaries.requirement_category SET description = 'Создание онлайн конференции', has_agreement = false, requirement_category_type_id = 1 WHERE id = 3;
UPDATE dictionaries.requirement_category SET description = 'Компьютер', has_agreement = false, requirement_category_type_id = 2 WHERE id = 4;
UPDATE dictionaries.requirement_category SET description = 'Ноутбук', has_agreement = false, requirement_category_type_id = 2 WHERE id = 5;
UPDATE dictionaries.requirement_category SET description = 'Перемещение рабочего места', has_agreement = false, requirement_category_type_id = 2 WHERE id = 6;
UPDATE dictionaries.requirement_category SET description = 'Принтер (МФУ)', has_agreement = false, requirement_category_type_id = 2 WHERE id = 7;
UPDATE dictionaries.requirement_category SET description = 'Принтер (МФУ) / Замена картриджа', has_agreement = false, requirement_category_type_id = 2 WHERE id = 8;
UPDATE dictionaries.requirement_category SET description = 'Переадресация электронной почты', has_agreement = false, requirement_category_type_id = 3 WHERE id = 9;
UPDATE dictionaries.requirement_category SET description = 'Создание почтового ящика', has_agreement = false, requirement_category_type_id = 3 WHERE id = 10;
UPDATE dictionaries.requirement_category SET description = 'Удаление почтового ящика', has_agreement = false, requirement_category_type_id = 3 WHERE id = 11;
UPDATE dictionaries.requirement_category SET description = 'Пополнение счета', has_agreement = false, requirement_category_type_id = 4 WHERE id = 12;
UPDATE dictionaries.requirement_category SET description = 'Другое', has_agreement = false, requirement_category_type_id = 5 WHERE id = 13;
UPDATE dictionaries.requirement_category SET description = 'Настройка почтового ящика', has_agreement = false, requirement_category_type_id = 5 WHERE id = 14;
UPDATE dictionaries.requirement_category SET description = 'Настройка приложения', has_agreement = false, requirement_category_type_id = 5 WHERE id = 15;
UPDATE dictionaries.requirement_category SET description = '1С: CRM', has_agreement = false, requirement_category_type_id = 6 WHERE id = 16;
UPDATE dictionaries.requirement_category SET description = '1С: ECM', has_agreement = false, requirement_category_type_id = 6 WHERE id = 17;
UPDATE dictionaries.requirement_category SET description = '1С: ERP', has_agreement = false, requirement_category_type_id = 6 WHERE id = 18;
UPDATE dictionaries.requirement_category SET description = 'Завершение сеанса 1C', has_agreement = false, requirement_category_type_id = 6 WHERE id = 19;
UPDATE dictionaries.requirement_category SET description = 'Настройка', has_agreement = false, requirement_category_type_id = 6 WHERE id = 20;
UPDATE dictionaries.requirement_category SET description = 'Удаление', has_agreement = false, requirement_category_type_id = 6 WHERE id = 21;
UPDATE dictionaries.requirement_category SET description = 'Установка', has_agreement = false, requirement_category_type_id = 6 WHERE id = 22;
UPDATE dictionaries.requirement_category SET description = 'Подключение к Wi-Fi', has_agreement = false, requirement_category_type_id = 7 WHERE id = 23;
UPDATE dictionaries.requirement_category SET description = 'Настройка', has_agreement = false, requirement_category_type_id = 8 WHERE id = 24;
UPDATE dictionaries.requirement_category SET description = 'Другое', has_agreement = false, requirement_category_type_id = 9 WHERE id = 25;
UPDATE dictionaries.requirement_category SET description = 'Переадресация', has_agreement = false, requirement_category_type_id = 9 WHERE id = 26;
UPDATE dictionaries.requirement_category SET description = 'Предоставление записи разговора', has_agreement = false, requirement_category_type_id = 9 WHERE id = 27;


alter table dictionaries.requirement_category
    add constraint fk_requirement_category_requirement_category_type
        foreign key (requirement_category_type_id) references dictionaries.requirement_category_type
            on delete cascade;

create index ix_requirement_category_requirement_category_type_id
    on dictionaries.requirement_category (requirement_category_type_id);

create unique index ix_requirement_category_description_requirement_category_type_
    on dictionaries.requirement_category (description, requirement_category_type_id);