create table business.file (
    id integer generated by default as identity constraint pk_file primary key,
    uid varchar(32) not null,
    name varchar(256) not null,
    upload_user_id integer constraint fk_file_user_upload_user_id references admin."user" on delete cascade,
    creation_date timestamp with time zone not null
);

alter table
    business.file owner to postgres;

create unique index ix_file_uid on business.file (uid);

create index ix_file_upload_user_id on business.file (upload_user_id);