create table business.requirement_link_notification
(
    id              integer generated by default as identity
        constraint pk_requirement_link_notification
            primary key,
    notification_id integer not null
        constraint fk_requirement_link_notification_notification_notification_id
            references business.notification
            on delete cascade,
    requirement_id  integer not null
        constraint fk_requirement_link_notification_requirement_requirement_id
            references business.requirement
            on delete cascade
);

alter table business.requirement_link_notification
    owner to postgres;

create unique index ix_requirement_link_notification_notification_id
    on business.requirement_link_notification (notification_id);

create index ix_requirement_link_notification_requirement_id
    on business.requirement_link_notification (requirement_id);